### ISSUE TITLE
Could you share the einschlafen-10s-AIRs dataset please?

### ISSUE THREAD

**Issue by iou2much** [jonashaag/speech-enhancement#1]
Could you share the einschlafen-10s-AIRs dataset please? I want to try out the DCUnet but cannot find it anywhere on the internet. It would be a great help. Thank you

**Comment by jonashaag** [comment]
Hi! It's not an actual dataset, just a bunch of test files that I assembled. I recommend DNS dataset + https://github.com/jonashaag/RealRIRs

**Comment by jonashaag** [comment]
Btw, AIR = Aachen Impulse Response, which is also part of https://github.com/jonashaag/RealRIRs

**Comment by iou2much** [comment]
Thank you so much for your reply and your work. It really helps a lot.
